### ISSUE TITLE
Missing demo source and documentation

### ISSUE THREAD

**Issue by saada** [Hellenic/react-hexgrid#1]
The demo shown doesn't really have much source code such as the applied CSS, what createBoard() returns? actions? configs? the props passed to the Board component?

It would be great if I could just run the same demo you generated your screenshot with.

**Comment by Hellenic** [comment]
Hey!
I made this for one of my personal projects and that's why it doesn't have any documentation. But nice to see that somebody is using (or trying to) it!

I added an example, https://github.com/Hellenic/react-hexgrid/tree/master/examples/basic-board
and also fixed the example code. Hoping to add some documentation at some point as well.

**Comment by saada** [comment]
cool, thanks!

**Comment by awatson1978** [comment]
Hi!  Fantastic work!  The grid loads up great in my app, and works seamlessly with video backgrounds.  

Any advice on how to swap out the coordinates with custom text?  Or the best way to bind actions to the hex tiles?  Would love to use this as a high level menu of sorts, and just add some 'Router.go()' or href links to each tile.

**Comment by Hellenic** [comment]
Hey! Thanks, cool if somebody finds it useful :)
That's a good question. It's somewhat possible but that part is still a bit work in progress, though I haven't had a change to work on it for a long time now. So it can be done but it's definitely not pretty yet.

It's possible to pass actions as a props and it will fall down all the way to the tiles. I have another project where I'm using this:
Passing the actions https://github.com/Hellenic/Cardeon/blob/master/game/src/components/Board.js#L20
and the actual actions (Redux actions + reducers): https://github.com/Hellenic/Cardeon/blob/master/game/src/actions/grid.js and 
https://github.com/Hellenic/Cardeon/blob/master/game/src/reducers/grid.js

So for example, when mouse is hovered over a tile it calls some action. Hex object is passed on along with the action. That hex object can have props (e.g. text) which is where you could insert your custom text. So you can change the text on each action if you want or already when the grid is generated, by modifying the hexagons list (grid.hexagons): https://github.com/Hellenic/react-hexgrid/blob/master/examples/basic-board/src/App.js#L15 

This is the class where the text etc. gets rendered: https://github.com/Hellenic/react-hexgrid/blob/master/src/HexShape.js

So... As I said, not so pretty yet! :D

**Comment by awatson1978** [comment]
Hey, that's clever!  I see what you're doing there.  

Thanks for documenting this.  Gotta think on this for a bit; but this definitely helps!

**Comment by Hellenic** [comment]
Added few examples and updated README. I believe those should be now quite covering for all the functionality that the library current offers.

Feel free to ask if you feel like something is missing! Closing this for now.

**Comment by awatson1978** [comment]
Dude.  This new API is **awesome**.  Total homerun.  Kudos to you.  This is absolutely fantastic work.
