### ISSUE TITLE
Passing 100% in HexGrid width and height

### ISSUE THREAD

**Issue by alcalyn** [Hellenic/react-hexgrid#15]
https://github.com/Hellenic/react-hexgrid/blob/6f745a2d91551a9f93d8e043439b25443c9b7130/src/HexGrid.js#L6-L7

Hi,

I can pass `100%` to width and height, but it throws: `Warning: Failed prop type: Invalid prop width of type string supplied to HexGrid, expected number.`

I think it should allows either a number or a string, like `100%`

Actually, it breaks integration testing

**Comment by Hellenic** [comment]
Good point, very true!

I'll have a look when I have a good spot. PR also welcome :)
