### ISSUE TITLE
New grid generator options missing

### ISSUE THREAD

**Issue by luisfrocha** [Hellenic/react-hexgrid#19]
Hello. I submitted the pull request with the spiral and circle options for the Grid generator. However, they don't seem to be included in any file in the lib or dist directories. Is there an additional step I need to take after "npm install react-hexgrid", or did I forget to perform a step before submitting the PR? I see the changes in the source files, but not in the installation in node_modules. (Full disclosure, this is my first PR submission ever)

**Comment by akollegger** [comment]
It looks like a new build hasn't been produced and published since your PR. `react-hexgrid: 1.0.2` was published about 2 months ago, so doesn't contain your updates. 

BTW, the spiral and ring look like nice additions!

**Comment by Hellenic** [comment]
Hey,

Right, very true! Thanks for reminding, I'll do that now.

**Comment by Hellenic** [comment]
Version 1.0.3 published just now with your changes
