### ISSUE TITLE
Path route conditions

### ISSUE THREAD

**Issue by thirdman** [Hellenic/react-hexgrid#26]
Hi. I'm enjoying this project!

Is there any easy/obvious approach towards making a path avoid some hexes? The use case for me is the idea of 'impassable' tiles...

<img width="455" alt="screen shot" src="https://user-images.githubusercontent.com/932337/52529285-cbed2d80-2d21-11e9-8e7a-ef4024c0bb18.png">

_(I want my Mongolian Horde to not be able to go over Mt Everest!)_

Note: I recognise this is a side project, so I understand if you don't want to/have time to respond. 😀 It's not a big issue for me, just something I was wondering about.

**Comment by Hellenic** [comment]
Hey! Glad you've found this useful. That would be pretty neat feature but currently there's nothing for that. Easiest way to do something like that would be probably to write your own version of Path component: https://github.com/Hellenic/react-hexgrid/blob/master/src/Path.js

**Comment by thirdman** [comment]
I thought as much. Thanks!
