### ISSUE TITLE
Text Overflow out of Hexagon

### ISSUE THREAD

**Issue by Lucas-guida** [Hellenic/react-hexgrid#3]
Hi
I noticed when you insert a long string into the hexagon, the string overflows out of the hexagon boundary. Is there a way to allow the string to text wrap within a hexagon?

Thanks
![text overflow](https://cloud.githubusercontent.com/assets/20760943/21737166/697ea486-d444-11e6-98cb-f0cb0d064d0c.JPG)

**Comment by Hellenic** [comment]
Hey!
Currently there's no logic related to rendering the text. You might be able to work-around that using CSS for the text element, but might not be exactly what you're looking for.

That's on my list and I'll get to it at some point, but let me know if you'd like to contribute! :)

Cheers

**Comment by Hellenic** [comment]
It's been a while, but with the latest version it's not possible to add custom elements inside hexagon, so it's possible to achieve this through that. Something like this:
```
<Hexagon q={1} r={0} s={-1}>
    <text x="0" y="0.3em" textAnchor="middle">{children}</text>
</Hexagon>
