### ISSUE TITLE
Couple questions re HexUtils.js

### ISSUE THREAD

**Issue by luetkemj** [Hellenic/react-hexgrid#6]
https://github.com/Hellenic/react-hexgrid/blob/master/src/HexUtils.js#L72
This function can result in a hex with floating points. Should we round in this function or leave it up to the user? It makes sense to me to take the extra step unless there is value in the precision that I have overlooked.

https://github.com/Hellenic/react-hexgrid/blob/master/src/HexUtils.js#L84
Is there a reason you chose to include commas here? Seems like you could get away with just the values and make the ids a lot cleaner. "1,-2,3" => "1-23"

**Comment by Hellenic** [comment]
For the first one: Yeah, that's true. There's no specific reason to keep the precision so I think we could add rounding there.

For the second: No specific reason. That was even quite temporary way to make an ID for hexagon while I was testing out the patterns. So it's possible to change to format you suggested or even come up with better way to generate an ID.
