### ISSUE TITLE
HexUtils HexToPixel function clarification needed

### ISSUE THREAD

**Issue by tieje** [Hellenic/react-hexgrid#84]
Make a comment on what the `HexToPixel` function does in `HexUtils.ts`
I don't know what it does.

**Comment by parkerbjur** [comment]
Are you asking for clearer documentation above the function or has this issue been resolved because there is a short description of the function right now, but I can add more if need be.

**Comment by tieje** [comment]
Thanks for pointing this out. I did write these comments myself after talking with others about what the function does.

**Comment by parkerbjur** [comment]
Sweet, I did go through and do some more thorough documentation of all the functions in HexUtils. I will submit a PR today probably.

**Comment by tieje** [comment]
Ok, thanks.
