### ISSUE TITLE
The typing in the Layout component doesn't accept a mix of dynamic and static children

### ISSUE THREAD

**Issue by EbokianKnight** [Hellenic/react-hexgrid#99]
<img width="724" alt="Screen Shot 2022-08-27 at 8 38 22 AM" src="https://user-images.githubusercontent.com/10439329/187030606-39b23315-3065-464f-a5a3-4af7d3225fa6.png">

When dynamically adding tiles into the Layout component, the typing does not like it when you also add manual elements.

**Comment by jannikbuschke** [comment]
Am I guessing correct that when you put the Fragment outside of your .map(...) i.e. 
```jsx
<React.Fragment>{hexTiles.map(...)}</React.Fragment>
<Hexagon.../>
```
it works?

**Comment by EbokianKnight** [comment]
Yup
